### ISSUE TITLE
Issue when matching on state and county FIPS

### ISSUE THREAD

**Issue by theobes** [cbgoodman/countyfips#2]
I believe that after the latest update, the dataset contains two separate observations for counties named "St. ...": one starting with St. and another one starting with St. This is great, but I believe this is problematic when matching on State and County fips: for instance, when I run 

`countyfips, statefips(my_state_fips_codes) countyfips(my_two digit_county_fips_codes)`

I get the following error:

`variables state_fips county_fips do not uniquely identify observations in the using data`
`r(459)`

I was able to verify that the "St. ..." were the problematic observations, by running the following on the master countyfips data:

`bysort state_fips county_fips: gen counter = _n`
`tab counter`

I get the that 30 counties have a repeated observation. All of these are indeed counties named "St. ... "

**Comment by cbgoodman** [comment]
You are 100% correct about the source of the problem. I am reverting back to the original data file. You may have to delete the `countyfips.dta' file in your personal folder to regenerate the new file.
